name: 'call_workflow_Upload Python files to ec2'

on:
  push:
    branches:
      - stage
    paths:
      - 'App/functions/**'
  workflow_dispatch:
  
jobs:
  call-workflow:
    uses: infra-faci-pf/repo_infradx_cicd_main/.github/workflows/called_py_workflow.yml@main
    secrets: inherit
    with:
      AWS_ACCOUNT: 161479556163                                      # AWSアカウントID
      IAM_ROLE_NAME: infradx-stg-iam-role-oidc                       # IAM Role名
      INSTANCE_ID: "                   "                             # インスタンスID
      BUCKET_NAME: "infradx-stg-s3-bckt-cicd-161479556163"           # S3バケット名
      REPO_PATH: "App/functions/"                                    # リポジトリパス
      REPO: "repo_infradx_ap_PCM_0010"                               # リポジトリ名
      INSTANCE_PATH: "/infradx/app/infradx-batch-data/functions" 　  # インスタンスパス
