name: 'call_workflow_Upload Python files to ec2'

on:
  push:
    branches:
      - main
    paths:
      - 'App/functions/**'
  workflow_dispatch:
  
jobs:
  call-workflow:
    uses: infra-faci-pf/repo_infradx_cicd_main/.github/workflows/[digiline_dev]called_py_workflow.yml@main
    secrets: inherit
    with:
      AWS_ACCOUNT: 814396194035                                # AWSアカウントID
      IAM_ROLE_NAME: infradx-dev-iam-role-oidc                 # IAM Role名を記載
      instance-id: "i-040dcc2eaefbce22a"
      bucket-name: "sentan-python-app-deploy-test-bucket"
      path: "App/functions/"
      repo: "repo_infradx_ap_PCM_0010"
      file-name: "PCM_0010.py"
